# Generated by Django 4.1.2 on 2022-11-07 20:54

from django.db import migrations, models
import trip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True)),
                ('pin_logo', models.CharField(choices=[('', 'Default pin'), ('', 'Kayaking'), ('', 'Hiking'), ('', 'Climbing'), ('', 'Sight seeing')], default='', max_length=255)),
                ('future', models.BooleanField()),
                ('weblink', models.URLField(blank=True)),
                ('social_link', models.URLField(blank=True)),
                ('track_file', models.FileField(blank=True, upload_to=trip.models.user_directory_path)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
